#!/usr/bin/env node
/**
 * KATASHIRO CLI - AI Research & Analysis Tool
 *
 * @requirement REQ-CLI-001
 * @design DES-KATASHIRO-001 §2.6 CLI Interface
 */

import { Command } from 'commander';
import { createRequire } from 'module';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { WebSearchClient, WebScraper, TextAnalyzer, EntityExtractor, SummaryGenerator, DeepResearchOrchestrator, isOk, isErr } from './index.js';
import {
  createContent,
  isValidFormat,
  isValidProvider,
  parseNumberOption,
  formatSearchResult,
  formatError,
  truncateText
} from './cli-helpers.js';

// package.json からバージョンを取得
const require = createRequire(import.meta.url);
const pkg = require('../package.json');

/**
 * ファイル保存（ディレクトリがなければ自動作成）
 */
async function saveReport(filePath: string, content: string): Promise<void> {
  const dir = dirname(filePath);
  await mkdir(dir, { recursive: true });
  await writeFile(filePath, content, 'utf-8');
}

/**
 * Deep Research結果をMarkdownレポートに変換
 */
function generateMarkdownReport(topic: string, result: any, totalTime: string): string {
  const lines: string[] = [];
  const now = new Date().toISOString().split('T')[0];
  
  lines.push(`# ${topic} - Deep Research Report`);
  lines.push('');
  lines.push(`> Generated by KATASHIRO on ${now}`);
  lines.push('');
  
  // 統計
  lines.push('## 📈 統計');
  lines.push('');
  lines.push(`- 総イテレーション: ${result.statistics.totalIterations}`);
  lines.push(`- 総発見数: ${result.statistics.totalFindingsProcessed}`);
  lines.push(`- 総ノード数: ${result.statistics.totalNodesCreated}`);
  lines.push(`- 平均新規情報率: ${(result.statistics.averageNoveltyRate * 100).toFixed(1)}%`);
  lines.push(`- 処理時間: ${totalTime}秒`);
  lines.push('');
  
  // 主要な発見
  lines.push('## 📋 主要な発見');
  lines.push('');
  result.keyFindings.forEach((finding: any, i: number) => {
    lines.push(`### ${i + 1}. ${finding.title}`);
    lines.push('');
    lines.push(finding.summary);
    lines.push('');
  });
  
  // 推論チェーン
  if (result.reasoningChain && result.reasoningChain.length > 0) {
    lines.push('## 🧠 推論チェーン');
    lines.push('');
    result.reasoningChain.forEach((step: any) => {
      const typeLabels: Record<string, string> = {
        observation: '📊 観察',
        inference: '💭 推論',
        synthesis: '🔗 統合',
        conclusion: '✅ 結論',
      };
      const label = typeLabels[step.type] || step.type;
      lines.push(`${step.step}. **[${label}]** ${step.description} (信頼度: ${(step.confidence * 100).toFixed(0)}%)`);
      lines.push('');
    });
  }
  
  // Mermaidダイアグラム
  if (result.mermaidDiagrams) {
    lines.push('## 📊 ダイアグラム');
    lines.push('');
    
    lines.push('### ナレッジグラフ');
    lines.push('```mermaid');
    lines.push(result.mermaidDiagrams.knowledgeGraph);
    lines.push('```');
    lines.push('');
    
    lines.push('### 推論フロー');
    lines.push('```mermaid');
    lines.push(result.mermaidDiagrams.reasoningFlow);
    lines.push('```');
    lines.push('');
    
    lines.push('### 調査プロセス');
    lines.push('```mermaid');
    lines.push(result.mermaidDiagrams.researchProcess);
    lines.push('```');
    lines.push('');
    
    lines.push('### 発見事項の関係');
    lines.push('```mermaid');
    lines.push(result.mermaidDiagrams.findingsRelation);
    lines.push('```');
    lines.push('');
  }
  
  // 情報ソース
  lines.push('## 🔗 情報ソース');
  lines.push('');
  result.sources.forEach((source: any, i: number) => {
    lines.push(`${i + 1}. [${source.title}](${source.url})`);
  });
  lines.push('');
  
  return lines.join('\n');
}

const program = new Command();

program
  .name('katashiro')
  .description('KATASHIRO CLI - AI Research & Analysis Tool')
  .version(pkg.version, '-v, --version', 'バージョンを表示');

// 検索コマンド
program
  .command('search <query>')
  .description('Web検索を実行')
  .option('-n, --max <number>', '結果の最大件数', '10')
  .option('-p, --provider <provider>', '検索プロバイダー (duckduckgo|searxng)', 'duckduckgo')
  .option('-f, --format <format>', '出力形式 (json|text)', 'text')
  .action(async (query: string, options: { max: string; provider: string; format: string }) => {
    try {
      const client = new WebSearchClient();
      const provider = options.provider as 'duckduckgo' | 'searxng';
      const results = await client.search(query, { 
        maxResults: parseInt(options.max, 10),
        provider
      });
      
      if (options.format === 'json') {
        console.log(JSON.stringify(results, null, 2));
      } else {
        console.log(`\n🔍 "${query}" の検索結果: ${results.length}件\n`);
        for (const r of results) {
          console.log(`📄 ${r.title}`);
          console.log(`   ${r.url}`);
          if (r.snippet) {
            console.log(`   ${r.snippet.substring(0, 100)}...`);
          }
          console.log();
        }
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// スクレイピングコマンド
program
  .command('scrape <url>')
  .description('Webページの内容を取得')
  .option('-f, --format <format>', '出力形式 (json|text)', 'text')
  .option('-s, --summary', '要約を表示', false)
  .action(async (url: string, options: { format: string; summary: boolean }) => {
    try {
      const scraper = new WebScraper();
      const result = await scraper.scrape(url);
      
      if (isErr(result)) {
        console.error('❌ スクレイプエラー:', result.error.message);
        process.exit(1);
      }

      const page = result.value;
      
      if (options.format === 'json') {
        console.log(JSON.stringify(page, null, 2));
      } else {
        console.log(`\n📄 ${page.title}`);
        console.log(`🔗 ${page.url}`);
        console.log('\n---\n');
        
        if (options.summary) {
          const summarizer = new SummaryGenerator();
          const content = createContent(page.title, page.content, page.url);
          const summary = await summarizer.generateSummary(content, { maxLength: 500 });
          if (isOk(summary)) {
            console.log('📝 要約:\n');
            console.log(summary.value);
          }
        } else {
          console.log(page.content.substring(0, 2000));
          if (page.content.length > 2000) {
            console.log(`\n... (${page.content.length - 2000}文字省略)`);
          }
        }
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// 分析コマンド
program
  .command('analyze <text>')
  .description('テキストを分析（キーワード・感情分析）')
  .option('-f, --format <format>', '出力形式 (json|text)', 'text')
  .action(async (text: string, options: { format: string }) => {
    try {
      const analyzer = new TextAnalyzer();
      const result = await analyzer.analyze(text);
      
      if (options.format === 'json') {
        console.log(JSON.stringify(result, null, 2));
      } else {
        console.log('\n📊 テキスト分析結果\n');
        console.log(`🔑 キーワード: ${result.keywords.join(', ')}`);
        console.log(`💬 感情: ${result.sentiment.sentiment}`);
        console.log(`📈 感情スコア: ${result.sentiment.score.toFixed(2)}`);
        console.log(`📝 複雑度: ${result.complexity.level} (${result.complexity.score})`);
        console.log(`📄 単語数: ${result.wordCount}`);
        console.log(`📄 文数: ${result.sentenceCount}`);
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// エンティティ抽出コマンド
program
  .command('extract <text>')
  .description('テキストからエンティティを抽出')
  .option('-f, --format <format>', '出力形式 (json|text)', 'text')
  .action(async (text: string, options: { format: string }) => {
    try {
      const extractor = new EntityExtractor();
      const entities = await extractor.extract(text);
      
      if (options.format === 'json') {
        console.log(JSON.stringify(entities, null, 2));
      } else {
        console.log('\n🔍 エンティティ抽出結果\n');
        
        if (entities.persons.length > 0) {
          console.log(`👤 人名: ${entities.persons.join(', ')}`);
        }
        if (entities.organizations.length > 0) {
          console.log(`🏢 組織: ${entities.organizations.join(', ')}`);
        }
        if (entities.locations.length > 0) {
          console.log(`📍 場所: ${entities.locations.join(', ')}`);
        }
        if (entities.dates.length > 0) {
          console.log(`📅 日付: ${entities.dates.join(', ')}`);
        }
        if (entities.urls.length > 0) {
          console.log(`🔗 URL: ${entities.urls.join(', ')}`);
        }
        if (entities.emails.length > 0) {
          console.log(`📧 メール: ${entities.emails.join(', ')}`);
        }
        if (entities.phones.length > 0) {
          console.log(`📞 電話: ${entities.phones.join(', ')}`);
        }
        if (entities.money.length > 0) {
          console.log(`💰 金額: ${entities.money.join(', ')}`);
        }
        
        console.log(`\n📊 合計: ${entities.all.length}件のエンティティ`);
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// 要約コマンド
program
  .command('summarize <text>')
  .description('テキストを要約')
  .option('-l, --length <number>', '要約の最大文字数', '300')
  .option('-f, --format <format>', '出力形式 (json|text)', 'text')
  .action(async (text: string, options: { length: string; format: string }) => {
    try {
      const summarizer = new SummaryGenerator();
      const content = createContent('CLI Input', text);
      const result = await summarizer.generateSummary(content, { maxLength: parseInt(options.length, 10) });
      
      if (isErr(result)) {
        const error = result.error as Error;
        console.error('❌ 要約エラー:', error.message);
        process.exit(1);
      }

      const summary = result.value;
      
      if (options.format === 'json') {
        console.log(JSON.stringify({ summary, originalLength: text.length }, null, 2));
      } else {
        console.log('\n📝 要約結果\n');
        console.log(summary);
        console.log(`\n(元のテキスト: ${text.length}文字 → 要約: ${summary.length}文字)`);
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// =============================================================================
// deep-research コマンド
// =============================================================================
program
  .command('deep-research <topic>')
  .description('Deep Research - 反復的な深掘り調査を実行')
  .option('-i, --iterations <number>', '最大イテレーション数', '5')
  .option('-t, --threshold <number>', '収束閾値 (0.0-1.0)', '0.15')
  .option('-f, --focus <areas>', 'フォーカスエリア (カンマ区切り)')
  .option('--format <type>', '出力形式 (text/json)', 'text')
  .option('-o, --output <path>', 'レポート保存先 (デフォルト: ./Reports/<topic>.md)')
  .action(async (topic: string, options: { iterations: string; threshold: string; focus?: string; format: string; output?: string }) => {
    try {
      console.log(`\n🔬 Deep Research: "${topic}"\n`);
      console.log('設定:');
      console.log(`  - 最大イテレーション: ${options.iterations}`);
      console.log(`  - 収束閾値: ${options.threshold}`);
      if (options.focus) {
        console.log(`  - フォーカスエリア: ${options.focus}`);
      }
      console.log('\n調査を開始しています...\n');

      const orchestrator = new DeepResearchOrchestrator();
      const startTime = Date.now();

      // AsyncGenerator を使用して反復的に結果を取得
      for await (const state of orchestrator.research({
        topic,
        maxIterations: parseInt(options.iterations, 10),
        convergenceThreshold: parseFloat(options.threshold),
        focusAreas: options.focus ? options.focus.split(',').map(s => s.trim()) : undefined,
      })) {
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        
        console.log(`📊 イテレーション ${state.iteration}/${options.iterations} (${elapsed}s)`);
        console.log(`   フェーズ: ${state.phase}`);
        console.log(`   累計発見数: ${state.totalFindingsCount}`);
        console.log(`   新規情報率: ${(state.noveltyRate * 100).toFixed(1)}%`);
        console.log(`   収束スコア: ${(state.convergenceScore * 100).toFixed(1)}%`);
        
        if (state.gaps && state.gaps.length > 0) {
          const gapDescriptions = state.gaps.slice(0, 3).map(g => g.description);
          console.log(`   ギャップ: ${gapDescriptions.join(', ')}${state.gaps.length > 3 ? '...' : ''}`);
        }
        console.log();
      }

      // 最終結果を取得
      const result = orchestrator.getResult();
      const totalTime = ((Date.now() - startTime) / 1000).toFixed(1);

      if (!result) {
        console.error('❌ 結果の取得に失敗しました');
        process.exit(1);
      }

      if (options.format === 'json') {
        console.log(JSON.stringify(result, null, 2));
      } else {
        console.log('━'.repeat(60));
        console.log('🎯 Deep Research 完了\n');
        console.log(`📈 統計:`);
        console.log(`   - 総イテレーション: ${result.statistics.totalIterations}`);
        console.log(`   - 総発見数: ${result.statistics.totalFindingsProcessed}`);
        console.log(`   - 総ノード数: ${result.statistics.totalNodesCreated}`);
        console.log(`   - 平均新規情報率: ${(result.statistics.averageNoveltyRate * 100).toFixed(1)}%`);
        console.log(`   - 処理時間: ${totalTime}秒`);
        
        console.log('\n📋 主要な発見:');
        result.keyFindings.slice(0, 10).forEach((finding, i) => {
          console.log(`   ${i + 1}. ${finding.title}: ${finding.summary}`);
        });
        
        if (result.keyFindings.length > 10) {
          console.log(`   ... 他 ${result.keyFindings.length - 10} 件`);
        }
        
        // 推論チェーン（論理的説明）を表示
        if (result.reasoningChain && result.reasoningChain.length > 0) {
          console.log('\n🧠 推論チェーン（結論に至った論理的説明）:');
          result.reasoningChain.forEach((step) => {
            const typeLabels: Record<string, string> = {
              observation: '📊 観察',
              inference: '💭 推論',
              synthesis: '🔗 統合',
              conclusion: '✅ 結論',
            };
            const label = typeLabels[step.type] || step.type;
            console.log(`   ${step.step}. [${label}] ${step.description}`);
            console.log(`      信頼度: ${(step.confidence * 100).toFixed(0)}%`);
          });
        }
        
        // Mermaidダイアグラムを表示
        if (result.mermaidDiagrams) {
          console.log('\n📊 Mermaidダイアグラム:');
          
          console.log('\n### ナレッジグラフ (mindmap)');
          console.log('```mermaid');
          console.log(result.mermaidDiagrams.knowledgeGraph);
          console.log('```');
          
          console.log('\n### 推論フロー (flowchart)');
          console.log('```mermaid');
          console.log(result.mermaidDiagrams.reasoningFlow);
          console.log('```');
          
          console.log('\n### 調査プロセス (sequence)');
          console.log('```mermaid');
          console.log(result.mermaidDiagrams.researchProcess);
          console.log('```');
          
          console.log('\n### 発見事項の関係 (graph)');
          console.log('```mermaid');
          console.log(result.mermaidDiagrams.findingsRelation);
          console.log('```');
        }
        
        console.log('\n🔗 情報ソース:');
        result.sources.slice(0, 5).forEach((source, i) => {
          console.log(`   ${i + 1}. ${source.title} (${source.url})`);
        });
        
        if (result.sources.length > 5) {
          console.log(`   ... 他 ${result.sources.length - 5} 件`);
        }
        
        // レポートをファイルに保存
        const sanitizedTopic = topic.replace(/[<>:"/\\|?*]/g, '_').substring(0, 50);
        const outputPath = options.output || join('Reports', `${sanitizedTopic}.md`);
        
        // Markdownレポートを生成
        const reportContent = generateMarkdownReport(topic, result, totalTime);
        await saveReport(outputPath, reportContent);
        console.log(`\n📁 レポート保存: ${outputPath}`);
        
        console.log('\n💡 ヒント: --format json オプションで完全な結果を取得できます');
      }
    } catch (error) {
      console.error('❌ エラー:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

program.parse();
