/**
 * Command Helpers Unit Tests
 *
 * @task TSK-071
 */

import { describe, it, expect } from 'vitest';
import {
  formatSearchResults,
  formatAnalysis,
  formatResearchResults,
  formatSummary,
  formatReport,
  countWords,
  formatErrorMessage,
  validateInput,
  isValidSummaryStyle,
  isValidResearchDepth,
  isValidReportFormat,
  SUMMARY_STYLES,
  RESEARCH_DEPTHS,
  REPORT_FORMATS
} from '../../src/commands/command-helpers.js';

describe('Command Helpers', () => {
  describe('formatSearchResults', () => {
    it('should format search results as markdown', () => {
      const results = [
        { title: 'Result 1', url: 'https://example.com/1', snippet: 'Snippet 1' },
        { title: 'Result 2', url: 'https://example.com/2', snippet: 'Snippet 2' }
      ];
      const formatted = formatSearchResults('test query', results);

      expect(formatted).toContain('# Search Results: test query');
      expect(formatted).toContain('Found 2 results');
      expect(formatted).toContain('## [Result 1](https://example.com/1)');
      expect(formatted).toContain('Snippet 1');
      expect(formatted).toContain('---');
    });

    it('should handle empty results', () => {
      const formatted = formatSearchResults('empty', []);
      expect(formatted).toContain('Found 0 results');
    });

    it('should escape markdown special characters in query', () => {
      const formatted = formatSearchResults('test [query]', []);
      expect(formatted).toContain('# Search Results: test [query]');
    });
  });

  describe('formatAnalysis', () => {
    it('should format analysis as markdown', () => {
      const analysis = {
        wordCount: 100,
        entities: ['Entity A', 'Entity B'],
        topics: ['Topic 1', 'Topic 2'],
        sentiment: 'positive'
      };
      const formatted = formatAnalysis(analysis);

      expect(formatted).toContain('# Content Analysis');
      expect(formatted).toContain('**Word Count:** 100');
      expect(formatted).toContain('**Sentiment:** positive');
      expect(formatted).toContain('## Entities');
      expect(formatted).toContain('- Entity A');
      expect(formatted).toContain('## Topics');
      expect(formatted).toContain('- Topic 1');
    });

    it('should handle empty arrays', () => {
      const analysis = {
        wordCount: 0,
        entities: [],
        topics: [],
        sentiment: 'neutral'
      };
      const formatted = formatAnalysis(analysis);

      expect(formatted).toContain('**Word Count:** 0');
      expect(formatted).toContain('## Entities');
      expect(formatted).toContain('## Topics');
    });
  });

  describe('formatResearchResults', () => {
    it('should format research results as markdown', () => {
      const results = {
        summary: 'This is the research summary.',
        sources: ['https://source1.com', 'https://source2.com']
      };
      const formatted = formatResearchResults('AI Technology', results);

      expect(formatted).toContain('# Research: AI Technology');
      expect(formatted).toContain('## Summary');
      expect(formatted).toContain('This is the research summary.');
      expect(formatted).toContain('## Sources');
      expect(formatted).toContain('- https://source1.com');
      expect(formatted).toContain('*Generated by KATASHIRO*');
    });

    it('should handle empty sources', () => {
      const results = {
        summary: 'No sources found.',
        sources: []
      };
      const formatted = formatResearchResults('Test', results);
      expect(formatted).toContain('## Sources');
    });
  });

  describe('formatSummary', () => {
    it('should format short content without ellipsis', () => {
      const formatted = formatSummary('Short text', 'brief');
      expect(formatted).toContain('# Summary (brief)');
      expect(formatted).toContain('Short text');
      expect(formatted).not.toContain('...');
      expect(formatted).toContain('*Generated by KATASHIRO*');
    });

    it('should truncate long content with ellipsis', () => {
      const longText = 'A'.repeat(300);
      const formatted = formatSummary(longText, 'detailed');

      expect(formatted).toContain('# Summary (detailed)');
      expect(formatted).toContain('A'.repeat(200));
      expect(formatted).toContain('...');
    });

    it('should use custom max preview length', () => {
      const text = 'A'.repeat(100);
      const formatted = formatSummary(text, 'bullet', 50);

      expect(formatted).toContain('A'.repeat(50));
      expect(formatted).toContain('...');
    });
  });

  describe('formatReport', () => {
    it('should format report as markdown', () => {
      const formatted = formatReport('Annual Review', 'markdown');

      expect(formatted).toContain('# Report: Annual Review');
      expect(formatted).toContain('Format: markdown');
      expect(formatted).toContain('## Introduction');
      expect(formatted).toContain('## Conclusion');
      expect(formatted).toContain('*Generated by KATASHIRO*');
    });

    it('should include format in output', () => {
      const formatted = formatReport('Test', 'html');
      expect(formatted).toContain('Format: html');
    });
  });

  describe('countWords', () => {
    it('should count words correctly', () => {
      expect(countWords('Hello world')).toBe(2);
      expect(countWords('One two three four five')).toBe(5);
    });

    it('should handle multiple spaces', () => {
      expect(countWords('Hello   world')).toBe(2);
      expect(countWords('  leading and trailing  ')).toBe(3);
    });

    it('should handle empty string', () => {
      expect(countWords('')).toBe(0);
      expect(countWords('   ')).toBe(0);
    });

    it('should handle single word', () => {
      expect(countWords('word')).toBe(1);
    });

    it('should handle newlines and tabs', () => {
      expect(countWords('Hello\nworld\tthere')).toBe(3);
    });
  });

  describe('formatErrorMessage', () => {
    it('should format Error object', () => {
      const error = new Error('Connection failed');
      const message = formatErrorMessage('Network error', error);
      expect(message).toBe('Network error: Connection failed');
    });

    it('should handle non-Error objects', () => {
      const message = formatErrorMessage('Unknown issue', 'string error');
      expect(message).toBe('Unknown issue: Unknown error');
    });

    it('should handle null/undefined', () => {
      expect(formatErrorMessage('Test', null)).toBe('Test: Unknown error');
      expect(formatErrorMessage('Test', undefined)).toBe('Test: Unknown error');
    });
  });

  describe('validateInput', () => {
    it('should return true for valid strings', () => {
      expect(validateInput('valid')).toBe(true);
      expect(validateInput('   valid   ')).toBe(true);
    });

    it('should return false for empty/whitespace', () => {
      expect(validateInput('')).toBe(false);
      expect(validateInput('   ')).toBe(false);
    });

    it('should return false for null/undefined', () => {
      expect(validateInput(null)).toBe(false);
      expect(validateInput(undefined)).toBe(false);
    });
  });

  describe('isValidSummaryStyle', () => {
    it('should return true for valid styles', () => {
      expect(isValidSummaryStyle('brief')).toBe(true);
      expect(isValidSummaryStyle('detailed')).toBe(true);
      expect(isValidSummaryStyle('bullet')).toBe(true);
    });

    it('should return false for invalid styles', () => {
      expect(isValidSummaryStyle('invalid')).toBe(false);
      expect(isValidSummaryStyle('')).toBe(false);
      expect(isValidSummaryStyle('BRIEF')).toBe(false);
    });
  });

  describe('isValidResearchDepth', () => {
    it('should return true for valid depths', () => {
      expect(isValidResearchDepth('shallow')).toBe(true);
      expect(isValidResearchDepth('moderate')).toBe(true);
      expect(isValidResearchDepth('deep')).toBe(true);
    });

    it('should return false for invalid depths', () => {
      expect(isValidResearchDepth('invalid')).toBe(false);
      expect(isValidResearchDepth('')).toBe(false);
    });
  });

  describe('isValidReportFormat', () => {
    it('should return true for valid formats', () => {
      expect(isValidReportFormat('markdown')).toBe(true);
      expect(isValidReportFormat('html')).toBe(true);
      expect(isValidReportFormat('pdf')).toBe(true);
    });

    it('should return false for invalid formats', () => {
      expect(isValidReportFormat('docx')).toBe(false);
      expect(isValidReportFormat('')).toBe(false);
    });
  });

  describe('Constants', () => {
    it('should have correct SUMMARY_STYLES', () => {
      expect(SUMMARY_STYLES).toEqual(['brief', 'detailed', 'bullet']);
    });

    it('should have correct RESEARCH_DEPTHS', () => {
      expect(RESEARCH_DEPTHS).toEqual(['shallow', 'moderate', 'deep']);
    });

    it('should have correct REPORT_FORMATS', () => {
      expect(REPORT_FORMATS).toEqual(['markdown', 'html', 'pdf']);
    });
  });
});
