/**
 * CommandManager Helper Functions
 *
 * Extracted for better testability
 * @module katashiro
 * @task TSK-071
 */

/**
 * Search result type
 */
export interface SearchResult {
  title: string;
  url: string;
  snippet: string;
}

/**
 * Content analysis result type
 */
export interface AnalysisResult {
  wordCount: number;
  entities: string[];
  topics: string[];
  sentiment: string;
}

/**
 * Research results type
 */
export interface ResearchResults {
  summary: string;
  sources: string[];
}

/**
 * Format search results as markdown
 */
export function formatSearchResults(query: string, results: SearchResult[]): string {
  let md = `# Search Results: ${query}\n\n`;
  md += `Found ${results.length} results\n\n`;

  for (const result of results) {
    md += `## [${result.title}](${result.url})\n\n`;
    md += `${result.snippet}\n\n`;
    md += '---\n\n';
  }

  return md;
}

/**
 * Format content analysis as markdown
 */
export function formatAnalysis(analysis: AnalysisResult): string {
  let md = '# Content Analysis\n\n';
  md += `**Word Count:** ${analysis.wordCount}\n\n`;
  md += `**Sentiment:** ${analysis.sentiment}\n\n`;
  md += '## Entities\n\n';
  md += analysis.entities.map((e) => `- ${e}`).join('\n');
  md += '\n\n## Topics\n\n';
  md += analysis.topics.map((t) => `- ${t}`).join('\n');
  return md;
}

/**
 * Format research results as markdown
 */
export function formatResearchResults(topic: string, results: ResearchResults): string {
  let md = `# Research: ${topic}\n\n`;
  md += `## Summary\n\n${results.summary}\n\n`;
  md += '## Sources\n\n';
  md += results.sources.map((s) => `- ${s}`).join('\n');
  md += '\n\n*Generated by KATASHIRO*';
  return md;
}

/**
 * Format summary as markdown
 */
export function formatSummary(content: string, style: string, maxPreviewLength: number = 200): string {
  const preview = content.substring(0, maxPreviewLength);
  const ellipsis = content.length > maxPreviewLength ? '...' : '';
  return `# Summary (${style})\n\n${preview}${ellipsis}\n\n*Generated by KATASHIRO*`;
}

/**
 * Format report as markdown
 */
export function formatReport(topic: string, format: string): string {
  return `# Report: ${topic}\n\nFormat: ${format}\n\n## Introduction\n\n...\n\n## Conclusion\n\n...\n\n*Generated by KATASHIRO*`;
}

/**
 * Count words in content
 */
export function countWords(content: string): number {
  if (!content || !content.trim()) {
    return 0;
  }
  return content.trim().split(/\s+/).length;
}

/**
 * Format error message
 */
export function formatErrorMessage(message: string, error: unknown): string {
  const errorMessage = error instanceof Error ? error.message : 'Unknown error';
  return `${message}: ${errorMessage}`;
}

/**
 * Validate input is not empty
 */
export function validateInput(input: string | undefined | null): input is string {
  return typeof input === 'string' && input.trim().length > 0;
}

/**
 * Summary style options
 */
export const SUMMARY_STYLES = ['brief', 'detailed', 'bullet'] as const;
export type SummaryStyle = typeof SUMMARY_STYLES[number];

/**
 * Validate summary style
 */
export function isValidSummaryStyle(style: string): style is SummaryStyle {
  return SUMMARY_STYLES.includes(style as SummaryStyle);
}

/**
 * Research depth options
 */
export const RESEARCH_DEPTHS = ['shallow', 'moderate', 'deep'] as const;
export type ResearchDepth = typeof RESEARCH_DEPTHS[number];

/**
 * Validate research depth
 */
export function isValidResearchDepth(depth: string): depth is ResearchDepth {
  return RESEARCH_DEPTHS.includes(depth as ResearchDepth);
}

/**
 * Report format options
 */
export const REPORT_FORMATS = ['markdown', 'html', 'pdf'] as const;
export type ReportFormat = typeof REPORT_FORMATS[number];

/**
 * Validate report format
 */
export function isValidReportFormat(format: string): format is ReportFormat {
  return REPORT_FORMATS.includes(format as ReportFormat);
}
